### ISSUE TITLE
Support for Material Child Names and Material Child Count ?

### ISSUE THREAD

**Issue by androonuix** [Nuix/Export-Profile-Plus#2]
Hey @JuicyDragon !  Love that you added the "do not report on excluded items" option.  Great work.

I don't see Material Child Names and Material Child Count in the list of supported fields.  Would you consider adding these?  This lines up with a client request.  

Appreciatively,
-Androooooooo

**Comment by JuicyDragon** [comment]
Thank you!  I had thought of adding those as fields to the script at one point, but I realized they are both already present in Nuix:

![image](https://user-images.githubusercontent.com/11775738/52068822-4653cb80-2532-11e9-8ac1-215d112cddf3.png)

I'm trying not to re-invent any of the fields that are already in Nuix since you can build a regular Nuix metadata profile and have it included with the fields provided by the script in whatever operation you are performing by checking "Build Upon Base Profile":

![image](https://user-images.githubusercontent.com/11775738/52069079-e01b7880-2532-11e9-8c97-ca24b9a23058.png)

Does that satisfy the functionality you had in mind?
